# Generated by Django 2.2 on 2020-08-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('contact1', models.CharField(max_length=11)),
                ('contact2', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Club Members',
                'db_table': 'clubmembers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Joma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kisti', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunder.Club_Members')),
            ],
            options={
                'verbose_name_plural': 'Joma details',
                'db_table': 'joma',
                'ordering': ['-kisti'],
            },
        ),
    ]
